[package]
name = "wot_replay_parser"
version = "0.1.0"
edition = "2021"
authors = ["dacite <d4cite@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wot_replay_parser"
path = "src/lib.rs"

[[bin]]
name = "wot_replay_parser"
path = "src/main.rs"


[dependencies]
utils = { path = "../utils" }
anyhow = "1.0.52"
miniz_oxide = "0.4.4"
byteorder = "1.4.3"
rust-crypto = "0.2"
hex = "0.4.3"
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
enum-as-inner = "0.4.0"
image = "0.24.1"
derivative = "2.2.0"
macros = { path = "../macros"}
getset = "0.1.2"
time = "0.3.7"
enum_dispatch = "0.3.8"
nom = { version = "7.1.1", features = ["alloc"] }

[dev-dependencies]
criterion = "0.3.5"
env_logger = "0.8.4"

[[bench]]
name = "benchmark"
harness = false