wrap_comments = true
group_imports = "StdExternalCrate"
enum_discrim_align_threshold = 30
struct_field_align_threshold = 20
blank_lines_upper_bound = 2
fn_args_layout = "Compressed"
max_width = 110
comment_width = 110
reorder_impl_items = true
ignore = [
    "datfile_parser/src/lib/battle_results/battle_result_fields.rs"
]