[workspace]

members = [
    "datfile_parser",
    "replay_parser",
    "macros",
    "wot_types",
    "utils",
    "definition_parser",
    "examples/replay_parser_example",
    "examples/replay_parser_simple"
]
