[package]
name = "replay_version_sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wot_replay_parser = { path = "../../replay_parser" }
utils = { path = "../../utils", package = "wot-battle-results-parser-utils", version = "0.2.0"}
rayon = "1.5.3"