[package]
name = "replay_parser_simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wot_replay_parser = "0.1.0"
serde_json = "1.0.68"