[package]
name = "wot_constants"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unpickler = { path = "../unpickler" }
serde_json = "1.0.74"